name: Hello

on:
  workflow_call:
    inputs:
      diff-depth:
        required: false
        type: string
        default: "1"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "depth=${{ inputs.diff-depth }}"
